version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: bash -c "npm install --prefix theme/static_src && npm --prefix theme/static_src run build:tailwind && python manage.py migrate && python manage.py tailwind start && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db