# Generated by Django 4.0.8 on 2022-12-13 14:07

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('librairie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieux', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('participants', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None)),
                ('Books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books')),
                ('Librairie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librairie.librairie')),
            ],
        ),
    ]
