# Generated by Django 4.0.8 on 2022-12-23 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lecture', '0002_remove_lecture_participants_lecture_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='participants',
            field=models.ManyToManyField(default=[], related_name='lectures', to=settings.AUTH_USER_MODEL),
        ),
    ]
