# Generated by Django 4.0.8 on 2022-12-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='statut',
            field=models.BooleanField(default=False),
        ),
    ]
