# Generated by Django 4.0.8 on 2022-12-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.RemoveField(
            model_name='books',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='books',
            name='synopsis',
        ),
        migrations.AddField(
            model_name='books',
            name='collection',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='editeur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='jaquette',
            field=models.ImageField(blank=True, null=True, upload_to='jaquettes'),
        ),
    ]
