# Generated by Django 4.0.8 on 2022-12-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_delete_author_remove_books_published_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='jaquette',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
