# Generated by Django 4.0.8 on 2023-01-02 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librairie', '0002_librairie_ville'),
        ('books', '0003_books_borrowed_by_loan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='books',
            new_name='Books',
        ),
        migrations.AddField(
            model_name='loan',
            name='Librairie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='librairie.librairie'),
        ),
    ]
