# Generated by Django 4.0.8 on 2023-01-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_book_loan_books_loan_librairie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='Books',
            new_name='book',
        ),
    ]
