# Generated by Django 4.0.8 on 2022-12-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_lecturegroupes'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='Librairie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='date_emprut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='date_retour',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Librairie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('livres', models.ManyToManyField(to='books.books')),
            ],
        ),
    ]
