# Generated by Django 4.0.8 on 2022-12-12 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_books_librairie_books_date_emprut_books_date_retour_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Librairie',
        ),
    ]
