# Generated by Django 4.0.8 on 2022-12-12 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_delete_librairie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LectureGroupes',
        ),
    ]
