# Generated by Django 4.0.8 on 2023-02-08 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librairie', '0003_alter_librairie_ville'),
        ('books', '0007_remove_loan_returned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='books',
            new_name='book',
        ),
        migrations.AlterField(
            model_name='books',
            name='Librairie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='librairie.librairie'),
        ),
    ]
