# Generated by Django 4.0.8 on 2022-12-13 08:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture_groupe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturegroupes',
            name='librairie',
        ),
        migrations.AddField(
            model_name='lecturegroupes',
            name='participants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None),
        ),
    ]
