# Generated by Django 4.0.8 on 2023-01-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librairie', '0002_librairie_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librairie',
            name='ville',
            field=models.CharField(max_length=255),
        ),
    ]
